/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package defensesystem;

import java.awt.Color;
import java.awt.geom.Area;

/**
 *
 * @author User
 */
public class Submarine extends javax.swing.JFrame implements Observer{

    private int isSelectedValue=1;
    
    public Submarine() {
        initComponents();
        setVisible(true);
        btnSend.setForeground(Color.white);
        btnSend.setBackground(Color.green);
	btnSend.setOpaque(true);
        
        lblAreaClearMassege.setBackground(Color.black);
        lblAreaClearMassege.setOpaque(true);
        
        btnShoot.setEnabled(false);
        btnSonar.setEnabled(false);
        btnTomahawk.setEnabled(false);
        btnTrident.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        massageBox = new javax.swing.JTextArea();
        textBox = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        lblSubmarine = new javax.swing.JLabel();
        lblAreaClearMassege = new javax.swing.JLabel();
        chkPosition = new javax.swing.JCheckBox();
        btnTomahawk = new javax.swing.JButton();
        btnShoot = new javax.swing.JButton();
        btnSonar = new javax.swing.JButton();
        btnTrident = new javax.swing.JButton();
        OxigenSlider = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        massageBox.setColumns(20);
        massageBox.setRows(5);
        jScrollPane1.setViewportView(massageBox);

        textBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBoxActionPerformed(evt);
            }
        });

        btnSend.setBackground(new java.awt.Color(0, 255, 51));
        btnSend.setForeground(new java.awt.Color(255, 0, 0));
        btnSend.setText("SEND >");
        btnSend.setFocusable(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        lblSubmarine.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblSubmarine.setForeground(new java.awt.Color(51, 102, 0));
        lblSubmarine.setText("Submarine");

        lblAreaClearMassege.setBackground(new java.awt.Color(0, 0, 0));
        lblAreaClearMassege.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAreaClearMassege.setForeground(new java.awt.Color(255, 51, 51));
        lblAreaClearMassege.setText("Area Not Cleared");

        chkPosition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkPosition.setForeground(new java.awt.Color(0, 0, 204));
        chkPosition.setText("Position");
        chkPosition.setFocusable(false);
        chkPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPositionActionPerformed(evt);
            }
        });

        btnTomahawk.setBackground(new java.awt.Color(153, 255, 255));
        btnTomahawk.setText("Tomahawk");
        btnTomahawk.setFocusable(false);

        btnShoot.setBackground(new java.awt.Color(153, 255, 255));
        btnShoot.setText("Shoot");
        btnShoot.setFocusable(false);

        btnSonar.setBackground(new java.awt.Color(153, 255, 255));
        btnSonar.setText("Sonar Operation");
        btnSonar.setFocusable(false);
        btnSonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonarActionPerformed(evt);
            }
        });

        btnTrident.setBackground(new java.awt.Color(153, 255, 255));
        btnTrident.setText("Tridenr-2 Misslie");
        btnTrident.setFocusable(false);
        btnTrident.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTridentActionPerformed(evt);
            }
        });

        OxigenSlider.setBackground(new java.awt.Color(0, 255, 255));
        OxigenSlider.setMajorTickSpacing(20);
        OxigenSlider.setMinorTickSpacing(5);
        OxigenSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        OxigenSlider.setPaintLabels(true);
        OxigenSlider.setPaintTicks(true);
        OxigenSlider.setSnapToTicks(true);
        OxigenSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                OxigenSliderStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 204));
        jLabel2.setText("   Fuel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblAreaClearMassege, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkPosition))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTomahawk, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTrident, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSonar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(5, 5, 5)
                                    .addComponent(btnSend))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(OxigenSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSubmarine)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblSubmarine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OxigenSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAreaClearMassege, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTomahawk, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTrident, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnShoot, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSonar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textBox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        
        Observerble.getinstace().setMassage(textBox.getText(),lblSubmarine.getText());
        textBox.setText(null);
    }//GEN-LAST:event_btnSendActionPerformed

    private void textBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBoxActionPerformed

    private void chkPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPositionActionPerformed
        if(chkPosition.isSelected()){
            this.isSelectedValue=0;
        }else{
            this.isSelectedValue=1;
        }
    }//GEN-LAST:event_chkPositionActionPerformed

    private void OxigenSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_OxigenSliderStateChanged
        Observerble.getinstace().setJsliderFuelValue(OxigenSlider.getValue(),lblSubmarine.getText());
    }//GEN-LAST:event_OxigenSliderStateChanged

    private void btnTridentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTridentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTridentActionPerformed

    private void btnSonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSonarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider OxigenSlider;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    private javax.swing.JButton btnSonar;
    private javax.swing.JButton btnTomahawk;
    private javax.swing.JButton btnTrident;
    private javax.swing.JCheckBox chkPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAreaClearMassege;
    private javax.swing.JLabel lblSubmarine;
    private javax.swing.JTextArea massageBox;
    private javax.swing.JTextField textBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String mg,String name){
        if(name.equals("Defanses Branch")){
            massageBox.append(name+"  :  "+mg+"\n\n");
        }else if(name.equals(lblSubmarine.getText())){
             massageBox.append(">>>"+mg+"\n\n");
        }
        System.out.println("Sub"+mg);
    }

    @Override
    public void updateAreaClear(int value) {
        if(value==0){
            lblAreaClearMassege.setText("Area Clear");
            lblAreaClearMassege.setForeground(Color.green);
            lblAreaClearMassege.setBackground(Color.black);
            lblAreaClearMassege.setOpaque(true);
        }else{
            lblAreaClearMassege.setText("Area Not Clear");
            lblAreaClearMassege.setForeground(Color.red);
            lblAreaClearMassege.setBackground(Color.black);
            lblAreaClearMassege.setOpaque(true);
        }
        System.out.println("Submarien > "+value); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void updateJsliderValue(int value) {
        if(isSelectedValue==1){
            btnShoot.setEnabled(false);
            btnSonar.setEnabled(false);
            btnTomahawk.setEnabled(false);
            btnTrident.setEnabled(false);
        }else if(value < 20 && isSelectedValue==0){
            btnShoot.setEnabled(false);
        }
        if(value > 20 && isSelectedValue==0){
            btnShoot.setEnabled(true);
        }
        if(value > 30 && isSelectedValue==0){
            btnSonar.setEnabled(true);
        }else{
            btnSonar.setEnabled(false);
        }
        if(value > 40 && isSelectedValue==0){
            btnTomahawk.setEnabled(true);
        }else{
            btnTomahawk.setEnabled(false);
        }
        if(value > 50 && isSelectedValue==0){
            btnTrident.setEnabled(true);
        }else{
            btnTrident.setEnabled(false);
        }
    }


    @Override
    public void updateJsliderFuelValue(int value, String name) {
         //To change body of generated methods, choose Tools | Templates.
    }
}
